import java.awt.Toolkit;
import java.awt.event.*;
import java.awt.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAFKAT
 */
public class EditRecipient extends javax.swing.JFrame {
    private DBCon dbcon=new DBCon();
    
    /**
     * Creates new form EditDonor
     */
    public EditRecipient() {
        initComponents();
        this.setResizable(false);
        //getContentPane().setBackground(new Color(102,0,0));
    }

     public void close() {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        EditBt = new javax.swing.JButton();
        BackBt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Recipient");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Enter Recipient Id or Name To Edit");

        searchTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        EditBt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        EditBt.setText("Edit");
        EditBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtActionPerformed(evt);
            }
        });

        BackBt.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        BackBt.setText("Back");
        BackBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(BackBt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(EditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditBt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(BackBt)
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(630, 311));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EditBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtActionPerformed
        close();
       String SearchTxt=searchTxt.getText();
       RecipientUpdate r = new RecipientUpdate();
       String sql;
       
       if(SearchTxt.length()>=3 &&SearchTxt.length()<=5) {
                if(dbcon.CheckRecepient(SearchTxt).equals("found")) {
                
                r.setVisible(true);
                sql="SELECT *FROM recipient_table WHERE Id='"+SearchTxt+"'";
                MainClass m=null;
                m= dbcon.getrecipent(sql);
                r.IdNo.setText(m.getid());
                r.NameText.setText(m.getname());
                r.PhnNum.setText(m.getnum());
                r.AddrTxt.setText(m.getaddr());
                r.AgeTxt.setText(m.getage());
                r.Gender.setText(m.getgender());
                r.Blood_gr.setText(m.getblood_group());
                r.NumBag.setText(m.getnum_of_bag());
                }
                else {
                    JOptionPane.showMessageDialog(null, "Match Not Found !","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
       
        else if(SearchTxt.length()>5)  {
                
                if(dbcon.CheckRecepient(SearchTxt).equals("found")) {
                  r.setVisible(true);
                sql="SELECT *FROM recipient_table WHERE Name='"+SearchTxt.toLowerCase()+"'";
                MainClass m=null;
                m= dbcon.getrecipent(sql);
                r.IdNo.setText(m.getid());
                r.NameText.setText(m.getname());
                r.PhnNum.setText(m.getnum());
                r.AddrTxt.setText(m.getaddr());
                r.AgeTxt.setText(m.getage());
                r.Gender.setText(m.getgender());
                r.Blood_gr.setText(m.getblood_group());
                r.NumBag.setText(m.getnum_of_bag());
                }
                 else {
                    JOptionPane.showMessageDialog(null, "Match Not Found !","Error",JOptionPane.ERROR_MESSAGE);
                }
            }
          else if(SearchTxt.length()<3) {
           JOptionPane.showMessageDialog(null, "Incomplete Entries !" , "Error" ,JOptionPane.ERROR_MESSAGE);
       }
            
            else {
                JOptionPane.showMessageDialog(null, "Please write Something !");
            }
       
       
    }//GEN-LAST:event_EditBtActionPerformed

    private void BackBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtActionPerformed
        close();
        StartForm s =new StartForm();
        s.setVisible(true);
    }//GEN-LAST:event_BackBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDonor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDonor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBt;
    private javax.swing.JButton EditBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField searchTxt;
    // End of variables declaration//GEN-END:variables
}
