import javax.swing.*;
import java.awt.event.*;
import java.awt.*;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAFKAT
 */
public class RecipientForm extends javax.swing.JFrame {
    
    private DBCon dbcon=new DBCon();
    /**
     * Creates new form PatientForm
     */
    public RecipientForm() {
        initComponents();
        this.setResizable(false);
        //getContentPane().setBackground(new Color(102,0,0));
    }

    private void reset() {
        
        this.IdNo.setText("");
        this.NameText.setText("");
        this.PhnNum.setText("");
        this.AddrTxt.setText("");
        this.AgeTxt.setText("");
        this.GenderTxt.setSelectedItem("");
        this.BloodGr.setSelectedItem("");
        this.NumBag.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AgeTxt = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        nameLabel1 = new javax.swing.JLabel();
        GenderTxt = new javax.swing.JComboBox();
        contactLabel = new javax.swing.JLabel();
        PhnNum = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        AddrTxt = new javax.swing.JTextField();
        bloodgroupLabel = new javax.swing.JLabel();
        BloodGr = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        NumBag = new javax.swing.JTextField();
        BackBt = new javax.swing.JButton();
        SaveBt = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        IdNo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recipient Form");

        AgeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nameLabel.setText("Full Name");

        ageLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ageLabel.setText("Age");

        NameText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        NameText.setToolTipText("Must be greater than 6 letters");

        genderLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        genderLabel.setText("Gender");

        nameLabel1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        nameLabel1.setText("Recipient Form");
        nameLabel1.setPreferredSize(new java.awt.Dimension(127, 29));

        GenderTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GenderTxt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female", "Decline to State" }));

        contactLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        contactLabel.setText("Contact Number");

        PhnNum.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        PhnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhnNumActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Address");

        AddrTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        bloodgroupLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bloodgroupLabel.setText("Blood Group");

        BloodGr.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BloodGr.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "O-", "O+", "A-", "A+", "B-", "B+", "AB-", "AB+" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Number of Bag's");

        NumBag.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        BackBt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BackBt.setText("Back");
        BackBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtActionPerformed(evt);
            }
        });

        SaveBt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        SaveBt.setText("Save");
        SaveBt.setToolTipText("Click To Save Data");
        SaveBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Recipient Id No.");

        IdNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        IdNo.setToolTipText("Must be 3 to 5 letters");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(IdNo, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(bloodgroupLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contactLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(AgeTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BloodGr, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GenderTxt, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PhnNum, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(jLabel2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NumBag, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(BackBt, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(SaveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(AddrTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(nameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(genderLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GenderTxt)
                    .addComponent(IdNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhnNum, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddrTxt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumBag, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AgeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bloodgroupLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BloodGr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addComponent(BackBt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(49, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SaveBt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        setSize(new java.awt.Dimension(613, 551));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void close() {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void BackBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtActionPerformed
        close();
        StartForm s=new StartForm();
        s.setVisible(true);
    }//GEN-LAST:event_BackBtActionPerformed

    private void SaveBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtActionPerformed
        //dbcon = new DBCon();
        String sql;
        String idno=IdNo.getText();
        String name=NameText.getText().toLowerCase();
        String phnNum=PhnNum.getText();
        String address=AddrTxt.getText();
        String age=AgeTxt.getText();
        String gender=(String) GenderTxt.getSelectedItem();
        String blood_gr=(String) BloodGr.getSelectedItem();
        String num_of_bag=NumBag.getText();
        
        if(idno.length()>=3&& idno.length()<=5 && name.length()>5&&phnNum.length()>0&&address.length()>0
         &&age.length()>0&&gender.length()>0&&blood_gr.length()>0&&num_of_bag.length()>0){
            
        sql="INSERT INTO recipient_table(Id, Name,Phone_Number,Address,Age,Gender,Blood_Group,Number_Of_Bags)VALUES"
         + "('"+idno+"','"+name+"','"+phnNum+"','"+address+"','"+age+"','"+gender+"','"+blood_gr+"','"+num_of_bag+"')";
        
        if(dbcon.InsertionCheckRecepirnt(idno).equals("found")) {
        
        dbcon.Insert(sql);
        JOptionPane.showMessageDialog(null, "Successfully Insrted");
        reset();
         close();
        StartForm s= new StartForm();
        s.setVisible(true);
        }
        
        else {
            JOptionPane.showMessageDialog(null, "Id Already Exist !");
        }
        
        }
        else {
            JOptionPane.showMessageDialog(null, "Incomplete entries");
            
        }
        
        
       
    }//GEN-LAST:event_SaveBtActionPerformed

    private void PhnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhnNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhnNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddrTxt;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JButton BackBt;
    private javax.swing.JComboBox BloodGr;
    private javax.swing.JComboBox GenderTxt;
    private javax.swing.JTextField IdNo;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField NumBag;
    private javax.swing.JTextField PhnNum;
    private javax.swing.JButton SaveBt;
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel bloodgroupLabel;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    // End of variables declaration//GEN-END:variables
}
