
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAFKAT
 */
public class EightMemberForm extends javax.swing.JFrame {

    /**
     * Creates new form EightMemberForm
     */
    public EightMemberForm() {
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(168, 166, 166));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Member3Meal = new javax.swing.JTextField();
        Member5Taka = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Member1Taka = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        Member3Taka = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Member6Meal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        Member6Taka = new javax.swing.JTextField();
        Member2Meal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Member1Meal = new javax.swing.JTextField();
        Member2Taka = new javax.swing.JTextField();
        Member4Meal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        Member5Meal = new javax.swing.JTextField();
        Member7Meal = new javax.swing.JTextField();
        Member4Taka = new javax.swing.JTextField();
        Member7Taka = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        Member8Meal = new javax.swing.JTextField();
        Member8Taka = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        CalCulateBt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BackBt = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Eight Members Form");

        Member3Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member5Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Member 1");

        Member1Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member3Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Total Meal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Deposited Amount (Taka)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Member 6");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("Member 4");

        Member6Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setText("Member 5");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel5.setText("Member 3");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel11.setText("Member 7");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Member 2");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setText("Member 6");

        Member6Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member2Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Enter Tolat Meal And Monthly Deposit For Each Member ");

        Member1Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member2Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member4Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member5Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member7Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member4Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member7Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member8Meal.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        Member8Taka.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel12.setText("Member 8");

        CalCulateBt.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        CalCulateBt.setText("Calculate");
        CalCulateBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalCulateBtActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        BackBt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        BackBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backbt.png"))); // NOI18N
        BackBt.setText(" Back");
        BackBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtActionPerformed(evt);
            }
        });
        jMenu1.add(BackBt);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        jMenuItem1.setText(" Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel3)
                .addGap(52, 52, 52)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addGap(104, 104, 104)
                .addComponent(Member1Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member1Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel6)
                .addGap(104, 104, 104)
                .addComponent(Member2Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member2Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addGap(104, 104, 104)
                .addComponent(Member3Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member3Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel7)
                .addGap(104, 104, 104)
                .addComponent(Member4Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member4Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel8)
                .addGap(104, 104, 104)
                .addComponent(Member5Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member5Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(104, 104, 104)
                .addComponent(Member6Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(Member6Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(Member7Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(Member7Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(108, 108, 108)
                .addComponent(Member8Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(Member8Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addComponent(CalCulateBt))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member1Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member1Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member2Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member2Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member3Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member3Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member4Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member4Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member5Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member5Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member6Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member6Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Member7Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Member7Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(8, 8, 8)
                .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member8Meal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Member8Taka, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CalCulateBt))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        public void close() {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void CalCulateBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalCulateBtActionPerformed

        close();
        EightMemberDisplay f = new EightMemberDisplay();

        String mMember1=this.Member1Meal.getText();
        String mMember2=this.Member2Meal.getText();
        String mMember3=this.Member3Meal.getText();
        String mMember4=this.Member4Meal.getText();
        String mMember5=this.Member5Meal.getText();
        String mMember6=this.Member6Meal.getText();
        String mMember7=this.Member7Meal.getText();
        String mMember8=this.Member8Meal.getText();

        String tMember1=this.Member1Taka.getText();
        String tMember2=this.Member2Taka.getText();
        String tMember3=this.Member3Taka.getText();
        String tMember4=this.Member4Taka.getText();
        String tMember5=this.Member5Taka.getText();
        String tMember6=this.Member6Taka.getText();
        String tMember7=this.Member7Taka.getText();
        String tMember8=this.Member8Taka.getText();

        if(mMember1.length()>0 && mMember2.length()>0 && mMember3.length()>0 && mMember4.length()>0 && mMember5.length()>0 && mMember6.length()>0 && mMember7.length()>0 && mMember8.length()>0 &&
            tMember1.length()>0 && tMember2.length()>0 && tMember3.length()>0 && tMember4.length()>0 && tMember5.length()>0 && tMember6.length()> 0&& tMember7.length()>0 && tMember8.length()>0) {

            Double MealMember1=Double.parseDouble(this.Member1Meal.getText());
            Double MealMember2=Double.parseDouble(this.Member2Meal.getText());
            Double MealMember3=Double.parseDouble(this.Member3Meal.getText());
            Double MealMember4=Double.parseDouble(this.Member4Meal.getText());
            Double MealMember5=Double.parseDouble(this.Member5Meal.getText());
            Double MealMember6=Double.parseDouble(this.Member6Meal.getText());
            Double MealMember7=Double.parseDouble(this.Member7Meal.getText());
            Double MealMember8=Double.parseDouble(this.Member8Meal.getText());

            Double TakaMember1=Double.parseDouble(this.Member1Taka.getText());
            Double TakaMember2=Double.parseDouble(this.Member2Taka.getText());
            Double TakaMember3=Double.parseDouble(this.Member3Taka.getText());
            Double TakaMember4=Double.parseDouble(this.Member4Taka.getText());
            Double TakaMember5=Double.parseDouble(this.Member5Taka.getText());
            Double TakaMember6=Double.parseDouble(this.Member6Taka.getText());
            Double TakaMember7=Double.parseDouble(this.Member7Taka.getText());
            Double TakaMember8=Double.parseDouble(this.Member8Taka.getText());

            if(MealMember1>0 && MealMember2>0&& MealMember3>0 && MealMember4>0 && MealMember5>0 && MealMember6>0 && MealMember7>0 && MealMember8>0
                && TakaMember1>0 && TakaMember2>0 && TakaMember3>0 && TakaMember4>0 && TakaMember5>0 && TakaMember6>0 && TakaMember7>0 && TakaMember8>0) {

                Double TotalMeal=MealMember1+MealMember2+MealMember3+MealMember4+MealMember5+MealMember6+MealMember7+MealMember8;
                Double TotalTaka=TakaMember1+TakaMember2+TakaMember3+TakaMember4+TakaMember5+TakaMember6+TakaMember7+TakaMember8;

                Double MealRate=TotalTaka/TotalMeal;

                Double Member1Cal=TakaMember1-(MealMember1*MealRate);

                Double Member2Cal=TakaMember2-(MealMember2*MealRate);

                Double Member3Cal=TakaMember3-(MealMember3*MealRate);

                Double Member4Cal=TakaMember4-(MealMember4*MealRate);

                Double Member5Cal=TakaMember5-(MealMember5*MealRate);

                Double Member6Cal=TakaMember6-(MealMember6*MealRate);

                Double Member7Cal=TakaMember7-(MealMember7*MealRate);
                
                Double Member8Cal=TakaMember8-(MealMember8*MealRate);

                f.setVisible(true);

                MealRate=Math.round(MealRate*1000)/1000.00;
                f.MealRate.setText(String.valueOf(MealRate));

                if(Member1Cal<0) {
                    Member1Cal=Math.round(Member1Cal*1000)/1000.00;
                    f.Member1Meal.setText(String.valueOf(Math.abs(Member1Cal)));
                }
                else {
                    Member1Cal=Math.round(Member1Cal*1000)/1000.00;
                    f.Member1Taka.setText(String.valueOf(Math.abs(Member1Cal)));
                }

                if(Member2Cal<0) {
                    Member2Cal=Math.round(Member2Cal*1000)/1000.00;
                    f.Member2Meal.setText(String.valueOf(Math.abs(Member2Cal)));
                }
                else {
                    Member2Cal=Math.round(Member2Cal*1000)/1000.00;
                    f.Member2Taka.setText(String.valueOf(Math.abs(Member2Cal)));
                }
                if(Member3Cal<0) {
                    Member3Cal=Math.round(Member3Cal*1000)/1000.00;
                    f.Member3Meal.setText(String.valueOf(Math.abs(Member3Cal)));
                }
                else {
                    Member3Cal=Math.round(Member3Cal*1000)/1000.00;
                    f.Member3Taka.setText(String.valueOf(Math.abs(Member3Cal)));
                }
                if(Member4Cal<0) {
                    Member4Cal=Math.round(Member4Cal*1000)/1000.00;
                    f.Member4Meal.setText(String.valueOf(Math.abs(Member4Cal)));
                }
                else {
                    Member4Cal=Math.round(Member4Cal*1000)/1000.00;
                    f.Member4Taka.setText(String.valueOf(Math.abs(Member4Cal)));
                }
                if(Member5Cal<0) {
                    Member5Cal=Math.round(Member5Cal*1000)/1000.00;
                    f.Member5Meal.setText(String.valueOf(Math.abs(Member5Cal)));
                }
                else {
                    Member5Cal=Math.round(Member5Cal*1000)/1000.00;
                    f.Member5Taka.setText(String.valueOf(Math.abs(Member5Cal)));
                }

                if(Member6Cal<0) {
                    Member6Cal=Math.round(Member6Cal*1000)/1000.00;
                    f.Member6Meal.setText(String.valueOf(Math.abs(Member6Cal)));
                }
                else {
                    Member6Cal=Math.round(Member6Cal*1000)/1000.00;
                    f.Member6Taka.setText(String.valueOf(Math.abs(Member6Cal)));
                }

                if(Member7Cal<0) {
                    Member7Cal=Math.round(Member7Cal*1000)/1000.00;
                    f.Member7Meal.setText(String.valueOf(Math.abs(Member7Cal)));
                }
                else {
                    Member7Cal=Math.round(Member7Cal*1000)/1000.00;
                    f.Member7Taka.setText(String.valueOf(Math.abs(Member7Cal)));
                }

                if(Member8Cal<0) {
                    Member8Cal=Math.round(Member8Cal*1000)/1000.00;
                    f.Member8Meal.setText(String.valueOf(Math.abs(Member8Cal)));
                }
                else {
                    Member8Cal=Math.round(Member8Cal*1000)/1000.00;
                    f.Member8Taka.setText(String.valueOf(Math.abs(Member8Cal)));
                }
                
            }
            else {

                JOptionPane.showMessageDialog(null, "Incomplete Entries", "Error", JOptionPane.ERROR_MESSAGE);
            }

        }
        else {

            JOptionPane.showMessageDialog(null, "Incomplete Entries", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CalCulateBtActionPerformed

    private void BackBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtActionPerformed
        
        close();
        FirstForm f = new FirstForm();
        f.setVisible(true);
       
    }//GEN-LAST:event_BackBtActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EightMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EightMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EightMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EightMemberForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EightMemberForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BackBt;
    private javax.swing.JButton CalCulateBt;
    private javax.swing.JTextField Member1Meal;
    private javax.swing.JTextField Member1Taka;
    private javax.swing.JTextField Member2Meal;
    private javax.swing.JTextField Member2Taka;
    private javax.swing.JTextField Member3Meal;
    private javax.swing.JTextField Member3Taka;
    private javax.swing.JTextField Member4Meal;
    private javax.swing.JTextField Member4Taka;
    private javax.swing.JTextField Member5Meal;
    private javax.swing.JTextField Member5Taka;
    private javax.swing.JTextField Member6Meal;
    private javax.swing.JTextField Member6Taka;
    private javax.swing.JTextField Member7Meal;
    private javax.swing.JTextField Member7Taka;
    private javax.swing.JTextField Member8Meal;
    private javax.swing.JTextField Member8Taka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
