
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAFKAT
 */
public class FirstForm extends javax.swing.JFrame {

    /**
     * Creates new form FirstForm
     */
    public FirstForm() {
        initComponents();
        this.setResizable(false);
        this.getContentPane().setBackground(new Color(168, 166, 166));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        TwoMemberBt = new javax.swing.JButton();
        ThreeMemberBt = new javax.swing.JButton();
        FourMemberBt = new javax.swing.JButton();
        FiveMemberBt = new javax.swing.JButton();
        SixMemeberBt = new javax.swing.JButton();
        SevenMemberBt = new javax.swing.JButton();
        EightMemberBt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ExitBt = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        AboutBt = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Meal Calculator");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Meal Calculator");

        TwoMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TwoMemberBt.setText("2 Members");
        TwoMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwoMemberBtActionPerformed(evt);
            }
        });

        ThreeMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ThreeMemberBt.setText("3 Members");
        ThreeMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThreeMemberBtActionPerformed(evt);
            }
        });

        FourMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FourMemberBt.setText("4 Members");
        FourMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FourMemberBtActionPerformed(evt);
            }
        });

        FiveMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FiveMemberBt.setText("5 Members");
        FiveMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveMemberBtActionPerformed(evt);
            }
        });

        SixMemeberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SixMemeberBt.setText("6 Members");
        SixMemeberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SixMemeberBtActionPerformed(evt);
            }
        });

        SevenMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SevenMemberBt.setText("7 Members");
        SevenMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SevenMemberBtActionPerformed(evt);
            }
        });

        EightMemberBt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EightMemberBt.setText("8 Members");
        EightMemberBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EightMemberBtActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        ExitBt.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        ExitBt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        ExitBt.setText(" Exit");
        ExitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtActionPerformed(evt);
            }
        });
        jMenu1.add(ExitBt);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        AboutBt.setText("About");
        AboutBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutBtActionPerformed(evt);
            }
        });
        jMenu2.add(AboutBt);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TwoMemberBt)
                                .addGap(31, 31, 31)
                                .addComponent(ThreeMemberBt)
                                .addGap(31, 31, 31)
                                .addComponent(FourMemberBt)
                                .addGap(31, 31, 31)
                                .addComponent(FiveMemberBt)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(SixMemeberBt)
                                .addGap(53, 53, 53)
                                .addComponent(SevenMemberBt)
                                .addGap(53, 53, 53)
                                .addComponent(EightMemberBt)
                                .addGap(49, 49, 49))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TwoMemberBt)
                    .addComponent(ThreeMemberBt)
                    .addComponent(FourMemberBt)
                    .addComponent(FiveMemberBt))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SixMemeberBt)
                    .addComponent(SevenMemberBt)
                    .addComponent(EightMemberBt))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
      public void close() {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    private void ThreeMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThreeMemberBtActionPerformed
     close();
       ThreeMemberForm f = new ThreeMemberForm();
        f.setVisible(true);
    }//GEN-LAST:event_ThreeMemberBtActionPerformed

    
    
    private void SevenMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SevenMemberBtActionPerformed
        close();
        SevenMemberForm s = new SevenMemberForm();
        s.setVisible(true);
    }//GEN-LAST:event_SevenMemberBtActionPerformed

    private void TwoMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwoMemberBtActionPerformed
       close();
        TwoMemberForm t = new TwoMemberForm();
       t.setVisible(true);
        
    }//GEN-LAST:event_TwoMemberBtActionPerformed

    private void FourMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FourMemberBtActionPerformed
      close();
        FourMemberForm f = new FourMemberForm();
       f.setVisible(true);
    }//GEN-LAST:event_FourMemberBtActionPerformed

    private void FiveMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveMemberBtActionPerformed
        close();
        FiveMemberForm f = new FiveMemberForm();
        f.setVisible(true);
    }//GEN-LAST:event_FiveMemberBtActionPerformed

    private void SixMemeberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SixMemeberBtActionPerformed
        close();
        SixMemberForm s = new SixMemberForm();
        s.setVisible(true);
    }//GEN-LAST:event_SixMemeberBtActionPerformed

    private void EightMemberBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EightMemberBtActionPerformed
        close();
        EightMemberForm e = new  EightMemberForm();
        e.setVisible(true);
    }//GEN-LAST:event_EightMemberBtActionPerformed

    private void ExitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitBtActionPerformed

    private void AboutBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutBtActionPerformed
        
        JOptionPane.showMessageDialog(null, "<html> <div color=red> Developed By : Md.Abdullah Al Shafi \n\nPlease give feedback on Facebook"
                + " \n\nwww.facebook.com/abdullahalshafi", "About", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_AboutBtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
            }UIManager.setLookAndFeel("com.jtattoo.plaf.graphite.GraphiteLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutBt;
    private javax.swing.JButton EightMemberBt;
    private javax.swing.JMenuItem ExitBt;
    private javax.swing.JButton FiveMemberBt;
    private javax.swing.JButton FourMemberBt;
    private javax.swing.JButton SevenMemberBt;
    private javax.swing.JButton SixMemeberBt;
    private javax.swing.JButton ThreeMemberBt;
    private javax.swing.JButton TwoMemberBt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
